// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhJLMTBJogWLHVVJvktwrprdjk6Kg4_xA',
    appId: '1:87654919025:web:d77c89f391d9f8049fe4d0',
    messagingSenderId: '87654919025',
    projectId: 'akm-bpddiy',
    authDomain: 'akm-bpddiy.firebaseapp.com',
    storageBucket: 'akm-bpddiy.appspot.com',
    measurementId: 'G-2ZSHNLBXXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB52NtckgR2FV9MCnsVKnL691hfaCuhCvU',
    appId: '1:87654919025:android:bb10f48c2ebbc49d9fe4d0',
    messagingSenderId: '87654919025',
    projectId: 'akm-bpddiy',
    storageBucket: 'akm-bpddiy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMwEJo38M814Oqv2N12MqSdD5ZdKeQvcI',
    appId: '1:87654919025:ios:6dec87d44fd480999fe4d0',
    messagingSenderId: '87654919025',
    projectId: 'akm-bpddiy',
    storageBucket: 'akm-bpddiy.appspot.com',
    iosClientId: '87654919025-ghv3cpjtv23eoir0lrmdh3u0gd2q1vgu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );
}
